# -*- coding: utf-8 -*-
"""text to image

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13TSEzwH_JQoQWHk7h3euSrv65gO09prQ
"""



! pip install min-dalle -q



from min_dalle import MinDalle

model = MinDalle(is_mega=True, is_reusable=True)



# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
text = "robots enjoying sunset in paris"
 seed = 6
 grid_size = 2
# 
# display(model.generate_image(text, seed, grid_size))
